#### This is a full EDA on the dataset

In [1]:
import os

import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [3]:
print(os.getcwd())

c:\Users\PCIVEW\Desktop\Learning\credit_card_fraud_detection_project\notebooks

In [2]:
#Reading the datset 
df = pd.read_csv('../data/credit_dataset.csv')
df.head()

,Unnamed: 0,ID,GENDER,CAR,REALITY,NO_OF_CHILD,INCOME,INCOME_TYPE,EDUCATION_TYPE,FAMILY_TYPE,HOUSE_TYPE,FLAG_MOBIL,WORK_PHONE,PHONE,E_MAIL,FAMILY SIZE,BEGIN_MONTH,AGE,YEARS_EMPLOYED,TARGET
0,0,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,1,0,0,0,2.0,29,59,3,0
1,1,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,1,0,1,1,1.0,4,52,8,0
2,2,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,1,0,1,1,1.0,26,52,8,0
3,3,5008810,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,1,0,1,1,1.0,26,52,8,0
4,4,5008811,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,1,0,1,1,1.0,38,52,8,0

In [4]:
df.shape

(25134, 20)

In [5]:
df.columns

Index(['Unnamed: 0', 'ID', 'GENDER', 'CAR', 'REALITY', 'NO_OF_CHILD', 'INCOME',
       'INCOME_TYPE', 'EDUCATION_TYPE', 'FAMILY_TYPE', 'HOUSE_TYPE',
       'FLAG_MOBIL', 'WORK_PHONE', 'PHONE', 'E_MAIL', 'FAMILY SIZE',
       'BEGIN_MONTH', 'AGE', 'YEARS_EMPLOYED', 'TARGET'],
      dtype='str')

In [6]:
df.describe()

,Unnamed: 0,ID,NO_OF_CHILD,INCOME,FLAG_MOBIL,WORK_PHONE,PHONE,E_MAIL,FAMILY SIZE,BEGIN_MONTH,AGE,YEARS_EMPLOYED,TARGET
count,25134.000000,2.513400e+04,25134.000000,2.513400e+04,25134.0,25134.000000,25134.000000,25134.000000,25134.000000,25134.000000,25134.000000,25134.000000,25134.000000
mean,12566.500000,5.078838e+06,0.512334,1.948339e+05,1.0,0.273812,0.292791,0.100660,2.294064,26.120594,40.536166,7.204106,0.016790
std,7255.705169,4.194102e+04,0.787785,1.045110e+05,0.0,0.445923,0.455052,0.300885,0.947590,16.439658,9.559474,6.414231,0.128486
min,0.000000,5.008806e+06,0.000000,2.700000e+04,1.0,0.000000,0.000000,0.000000,1.000000,0.000000,21.000000,0.000000,0.000000
25%,6283.250000,5.042228e+06,0.000000,1.350000e+05,1.0,0.000000,0.000000,0.000000,2.000000,12.000000,33.000000,3.000000,0.000000
50%,12566.500000,5.079004e+06,0.000000,1.800000e+05,1.0,0.000000,0.000000,0.000000,2.000000,24.000000,40.000000,5.000000,0.000000
75%,18849.750000,5.115604e+06,1.000000,2.250000e+05,1.0,1.000000,1.000000,0.000000,3.000000,39.000000,48.000000,10.000000,0.000000
max,25133.000000,5.150487e+06,19.000000,1.575000e+06,1.0,1.000000,1.000000,1.000000,20.000000,60.000000,67.000000,43.000000,1.000000

In [29]:
for col in df.columns:
    print(f" {col} : {df[col].unique()}")

 Unnamed: 0 : [    0     1     2 ... 25131 25132 25133]
 ID : [5008806 5008808 5008809 ... 5149838 5150049 5150337]
 GENDER : <StringArray>
['M', 'F']
Length: 2, dtype: str
 CAR : <StringArray>
['Y', 'N']
Length: 2, dtype: str
 REALITY : <StringArray>
['Y', 'N']
Length: 2, dtype: str
 NO_OF_CHILD : [ 0  3  1  2  4 14  5 19  7]
 INCOME : [ 112500.   270000.   135000.   130500.   157500.   405000.   211500.
  360000.   126000.   247500.   297000.   166500.   225000.   315000.
  148500.   202500.   450000.   180000.    90000.   765000.   229500.
  292500.    74250.   144000.   337500.   193500.   267750.   139500.
   67500.   252000.   900000.   279000.    76500.   234000.    81000.
  108000.   198000.   216000.    45000.   238500.   117000.  1350000.
   99000.   445500.   427500.   306000.   328500.   310500.   540000.
  171000.   675000.   121500.    72000.   184500.   189000.   243000.
   94500.   256500.   697500.   196650.    40500.   432000.   162000.
  103500.   257625.    58500.   207000.   720000.   261000.   175500.
  382500.   119250.    63000.   274500.    90900.   495000.   220500.
   49500.   630000.   585000.   145350.   173250.   531000.   387000.
 1125000.   283500.    36000.   179100.   265500.   118350.   123750.
  116653.5  153000.   324000.   351000.   441000.   227250.    54000.
   51750.   396000.   810000.    69750.    85500.   616500.   378000.
  234135.    74061.   168750.   472500.   391500.   364500.   661500.
  240750.   333000.   342000.   176400.   115200.   120150.   373500.
  146250.   213750.   346500.   191250.   132372.   159750.   132750.
   91530.   170302.5  265581.   184135.5  160200.   191700.   253800.
  369000.   176175.   190399.5  716323.5   78750.   288000.   222750.
   62653.5  607500.   215550.   122400.    60376.5  254700.   787500.
  140400.   185400.   129150.   612000.    31500.   562500.    69372.
  134995.5  301500.   164250.    60750.   171261.   128542.5  178200.
   73350.   124200.    82350.   634500.   459000.   143100.    87750.
  945000.   463500.   560250.    36900.    32400.   147150.   517500.
   27000.   990000.   355500.   140850.   195750.   101250.   423000.
  326250.   105750.   468000.   114750.    95850.    47250.   652500.
 1575000.   494100.   155250.   116100.   215100.   179271. ]
 INCOME_TYPE : <StringArray>
['Working', 'Commercial associate', 'State servant', 'Student', 'Pensioner']
Length: 5, dtype: str
 EDUCATION_TYPE : <StringArray>
['Secondary / secondary special',              'Higher education',
             'Incomplete higher',               'Lower secondary',
               'Academic degree']
Length: 5, dtype: str
 FAMILY_TYPE : <StringArray>
['Married', 'Single / not married', 'Civil marriage', 'Separated', 'Widow']
Length: 5, dtype: str
 HOUSE_TYPE : <StringArray>
[  'House / apartment',    'Rented apartment', 'Municipal apartment',
        'With parents',     'Co-op apartment',    'Office apartment']
Length: 6, dtype: str
 FLAG_MOBIL : [1]
 WORK_PHONE : [0 1]
 PHONE : [0 1]
 E_MAIL : [0 1]
 FAMILY SIZE : [ 2.  1.  5.  3.  4.  6. 15.  7. 20.  9.]
 BEGIN_MONTH : [29  4 26 38  5 42 17 16  8 22  7  3 25 30 31 19 34 24 18 39 13 55 43 11
 46 51  0 28 27 10  2 20 21 45 48 37 36 32 23 15 12  9  6  1 14 58 40 44
 35 59 56 47 33 60 53 41 49 57 50 54 52]
 AGE : [59 52 46 49 29 27 35 32 56 43 44 34 47 37 42 57 45 54 40 39 48 30 24 21
 28 33 36 26 50 41 58 51 31 38 53 22 25 55 60 61 62 23 64 63 65 66 67]
 YEARS_EMPLOYED : [ 3  8  2  4  6 12  9 19 15  5 13  7 17 30 16 11  1 10 24 14 25  0 20 27
 18 23 21 22 28 39 32 33 37 26 38 31 35 34 29 40 36 41 43]
 TARGET : [0 1]

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25134 entries, 0 to 25133
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      25134 non-null  int64
 1   ID              25134 non-null  int64
 2   GENDER          25134 non-null  str
 3   CAR             25134 non-null  str
 4   REALITY         25134 non-null  str
 5   NO_OF_CHILD     25134 non-null  int64
 6   INCOME          25134 non-null  float64
 7   INCOME_TYPE     25134 non-null  str
 8   EDUCATION_TYPE  25134 non-null  str
 9   FAMILY_TYPE     25134 non-null  str
 10  HOUSE_TYPE      25134 non-null  str
 11  FLAG_MOBIL      25134 non-null  int64
 12  WORK_PHONE      25134 non-null  int64
 13  PHONE           25134 non-null  int64
 14  E_MAIL          25134 non-null  int64
 15  FAMILY SIZE     25134 non-null  float64
 16  BEGIN_MONTH     25134 non-null  int64
 17  AGE             25134 non-null  int64
 18  YEARS_EMPLOYED  25134 non-null  int64
 19  TARGET          25134 non-null  int64
dtypes: float64(2), int64(11), str(7)
memory usage: 3.8 MB

In [31]:
#checking for null values 
df.isnull().sum()

Unnamed: 0        0
ID                0
GENDER            0
CAR               0
REALITY           0
NO_OF_CHILD       0
INCOME            0
INCOME_TYPE       0
EDUCATION_TYPE    0
FAMILY_TYPE       0
HOUSE_TYPE        0
FLAG_MOBIL        0
WORK_PHONE        0
PHONE             0
E_MAIL            0
FAMILY SIZE       0
BEGIN_MONTH       0
AGE               0
YEARS_EMPLOYED    0
TARGET            0
dtype: int64

In [32]:
#Checking for duplicates
df.duplicated().sum()

np.int64(0)

In [14]:
#Check categorical and numerical values

In [ ]:
#check for outliers